'use client';
import {useEffect,useState} from 'react';
import {Truck,ChevronRight,Settings2} from 'lucide-react';
import {nextDelivery,countdown,deliveryLabel} from '../lib/delivery.mjs';
const defaults={cutoff:'12:00',days:[1,2,3,4,5,6],badge:'SOLO CABA Y GBA',bg:'#F7FFFB',accent:'#09934F',badgeBg:'#191919',urgent:'#D92332',threshold:60,critical:10,free:false,blockedDates:''};
type Config=typeof defaults;
export default function Home(){
 const [cfg,setCfg]=useState<Config>(defaults); const [saved,setSaved]=useState(false); const [loaded,setLoaded]=useState(false); const [now,setNow]=useState<Date|null>(null);const [simulate,setSimulate]=useState('real');
 useEffect(()=>{const tick=()=>{const d=new Date();if(simulate!=='real'){const [h,m]=simulate.split(':').map(Number);d.setHours(h,m,27,0)}setNow(d)};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[simulate]);
 useEffect(()=>{try{const raw=localStorage.getItem('llega-hoy:config:v1');if(raw){const parsed=JSON.parse(raw);setCfg({...defaults,...parsed});setSaved(true)}}catch(e){console.warn('No se pudo recuperar configuración',e)}setLoaded(true)},[]);
 const save=()=>{try{localStorage.setItem('llega-hoy:config:v1',JSON.stringify(cfg));setSaved(true)}catch(e){alert('No se pudo guardar en este navegador')}};
 const exportConfig=()=>{const blob=new Blob([JSON.stringify(cfg,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='llega-hoy-config.json';a.click();URL.revokeObjectURL(url)};
 const result=now?nextDelivery(now,{cutoff:cfg.cutoff,days:cfg.days,blockedDates:cfg.blockedDates.split(',').map(s=>s.trim()).filter(Boolean)}):null;
 const urgent=!!result&&result.status==='today'&&result.seconds<=cfg.threshold*60;
 const critical=!!result&&result.status==='today'&&result.seconds<=cfg.critical*60;
 const accent=urgent?cfg.urgent:cfg.accent;
 const set=<K extends keyof Config>(key:K,value:Config[K])=>{setSaved(false);setCfg(prev=>({...prev,[key]:value}))};
 return <main className="shell"><header><span className="eyebrow"><Settings2 size={15}/> PROTOTIPO · V0.2</span><h1>Llega Hoy</h1><p>Widget compacto para entregas en CABA y GBA. Configurá el diseño y simulá el horario de corte.</p></header>
 <div className="layout"><section className="preview-panel"><div className="panel-heading">VISTA PREVIA <span>Producto · Desktop / Mobile</span></div><div className="product-mock"><div className="fake-photo">FOTO DEL PRODUCTO</div><div className="fake-details"><div className="fake-line short"/><div className="fake-line"/><div className="fake-price">$57.700</div><div className="fake-line short"/><div className="delivery-wrap"><div className="floating-badge" style={{background:cfg.badgeBg}}>{cfg.badge}</div><div className="delivery" style={{background:urgent?'#FFF8F8':cfg.bg,borderColor:urgent?'#FFC8CE':'#BFE8D6'}}><Truck className="truck" color={accent} size={29}/><div className="delivery-copy"><strong>{result?(cfg.free&&result.status==='today'?'Llega gratis hoy':deliveryLabel(result)):'Calculando...'}</strong><span>{result?.status==='today'?<>Comprando dentro de los próximos <b style={{color:accent}}>{countdown(result.seconds)}</b></>:result?.status==='tomorrow'?'Comprando ahora, tu pedido llega mañana.':result?.status==='later'?'Comprando ahora, llega el próximo día habilitado.':'Consultá las opciones de entrega.'}</span></div><ChevronRight color="#87939B" size={22}/></div></div><div className="fake-button">AGREGAR AL CARRITO</div></div></div><p className="notice">La vista previa usa la hora local de tu navegador. En producción, fijaremos la zona horaria de cada tienda y validaremos los días de reparto.</p></section>
 <aside className="settings"><h2>Configuración</h2><div className="save-actions"><button type="button" onClick={save} disabled={!loaded}>Guardar cambios</button><button type="button" className="secondary" onClick={exportConfig}>Exportar JSON</button></div><p className="save-message">{saved?"✓ Guardado en este navegador":"Cambios sin guardar"}</p><label>Simular horario<select value={simulate} onChange={e=>setSimulate(e.target.value)}><option value="real">Hora real</option><option value="09:30">09:30</option><option value="11:00">11:00</option><option value="11:30">11:30</option><option value="11:59">11:59 (últimos segundos)</option><option value="12:30">12:30 (después del corte)</option></select></label><label>Hora de corte<input type="time" value={cfg.cutoff} onChange={e=>set('cutoff',e.target.value)}/></label><div className="field"><span>Días de entrega</span><div className="days">{['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'].map((d,i)=><label key={d} className="day"><input type="checkbox" checked={cfg.days.includes(i)} onChange={e=>set('days',e.target.checked?[...cfg.days,i]:cfg.days.filter(x=>x!==i))}/>{d}</label>)}</div></div><label>Texto del badge<input value={cfg.badge} onChange={e=>set('badge',e.target.value)}/></label><label>Fechas sin entrega (AAAA-MM-DD, separadas por comas)<input placeholder="2026-12-25, 2027-01-01" value={cfg.blockedDates} onChange={e=>set('blockedDates',e.target.value)}/></label><div className="colors"><label>Color principal<input type="color" value={cfg.accent} onChange={e=>set('accent',e.target.value)}/></label><label>Fondo<input type="color" value={cfg.bg} onChange={e=>set('bg',e.target.value)}/></label><label>Badge<input type="color" value={cfg.badgeBg} onChange={e=>set('badgeBg',e.target.value)}/></label><label>Urgencia<input type="color" value={cfg.urgent} onChange={e=>set('urgent',e.target.value)}/></label></div><label>Mostrar “gratis” <input type="checkbox" checked={cfg.free} onChange={e=>set('free',e.target.checked)}/></label><label>Activar urgencia a los (min)<input type="number" min="1" max="180" value={cfg.threshold} onChange={e=>set('threshold',Number(e.target.value))}/></label><label>Urgencia máxima a los (min)<input type="number" min="1" max="60" value={cfg.critical} onChange={e=>set('critical',Number(e.target.value))}/></label><div className="status">{critical?'🔴 Últimos minutos':urgent?'🔴 Cuenta regresiva con segundos':'🟢 Estado normal'}</div><p className="fineprint">Los cambios se guardan únicamente en este navegador. Exportá el JSON como respaldo. Todavía no se publican en Tiendanube; “gratis” solo si aplica al envío en el día.</p></aside></div></main>
}
